Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -45,3 +45,11 @@ jobs:
       working-directory: ${{github.workspace}}/build
       shell: bash
       run: ${{github.workspace}}/build/test/Linqplusplus_test --gtest_output="xml"
+
+    - name: Check Test Success
+      working-directory: ${{github.workspace}}/build
+      shell: bash
+      run: if cat test_detail.xml | grep FAIL ; echo $? ; then echo "TEST_FAIL" >> $TEST_RESULT ; else echo "TEST_SUCCESS" >> $TEST_RESULT fi
+      
+    - name: Print test
+      run: echo $TEST_RESULT
